spring:
  application:
    name: order
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 412013
    url: jdbc:mysql://10.10.10.103:3306/SpringColudShell?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://10.10.10.103:8761/eureka/
  instance:
    hostname: localhost
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

